-- ============================================================
-- ระบบบริหารจัดการชั้นวางสินค้า (RAG) — โครงสร้างฐานข้อมูล PostgreSQL
-- แปลงจาก schema.sql (SQLite) สำหรับใช้กับ Supabase
--
-- แนวคิดเหมือนเดิม: ตำแหน่งจัดเก็บ 1 ช่อง เก็บสินค้าได้ 1 รายการ
--                  ทุกการเคลื่อนย้ายถูกบันทึกเป็นประวัติที่ลบไม่ได้
--
-- หมายเหตุเรื่องเวลา: ใช้ (now() AT TIME ZONE 'Asia/Bangkok') ทุกจุด จึงได้เวลาไทยเสมอ
--                    ไม่ขึ้นกับ session timezone เหมือน datetime('now','localtime') เดิม
-- ============================================================

-- ---------- ผู้ใช้งาน ----------
CREATE TABLE IF NOT EXISTS users (
  user_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT NOT NULL UNIQUE,
  full_name     TEXT NOT NULL,
  role          TEXT NOT NULL CHECK (role IN ('ADMIN','STAFF','VIEWER')),
  password_hash TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at    TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);

CREATE TABLE IF NOT EXISTS sessions (
  token      TEXT PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(user_id),
  expires_at TIMESTAMP NOT NULL
);

-- ---------- โครงสร้างคลัง: คลังสินค้า → โซน → ชั้นวาง (RACK) → ตำแหน่ง ----------
CREATE TABLE IF NOT EXISTS warehouses (
  warehouse_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wh_code      TEXT NOT NULL UNIQUE,
  wh_name      TEXT NOT NULL,
  address      TEXT,
  grid_cols    INTEGER NOT NULL DEFAULT 10 CHECK (grid_cols BETWEEN 1 AND 40),
  grid_rows    INTEGER NOT NULL DEFAULT 8  CHECK (grid_rows BETWEEN 1 AND 40),
  note         TEXT,
  status       TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);

-- warehouse_id / color เดิมเพิ่มด้วย ALTER TABLE ใน SQLite — ที่นี่ประกาศตรง ๆ ได้เลย
CREATE TABLE IF NOT EXISTS zones (
  zone_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_code    TEXT NOT NULL UNIQUE,
  zone_name    TEXT NOT NULL,
  warehouse_id INTEGER REFERENCES warehouses(warehouse_id),
  color        TEXT NOT NULL DEFAULT '#2563eb',
  status       TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);

CREATE TABLE IF NOT EXISTS rags (
  rag_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rag_no       TEXT NOT NULL UNIQUE,
  zone_id      INTEGER NOT NULL REFERENCES zones(zone_id),
  total_levels INTEGER NOT NULL CHECK (total_levels BETWEEN 1 AND 20),
  total_depths INTEGER NOT NULL CHECK (total_depths BETWEEN 1 AND 30),
  note         TEXT,
  pos_x        INTEGER,   -- ตำแหน่งบนผังพื้นคลัง (คอลัมน์)
  pos_y        INTEGER,   -- ตำแหน่งบนผังพื้นคลัง (แถว)
  status       TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);

CREATE TABLE IF NOT EXISTS locations (
  location_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_code TEXT NOT NULL UNIQUE,          -- เช่น FG-A01-L2-D3
  rag_id        INTEGER NOT NULL REFERENCES rags(rag_id) ON DELETE CASCADE,
  level         INTEGER NOT NULL,              -- ชั้น (1 = ล่างสุด)
  depth         INTEGER NOT NULL,              -- ตอน (1 = หน้าสุด)
  status        TEXT NOT NULL DEFAULT 'EMPTY' CHECK (status IN ('EMPTY','OCCUPIED','DISABLED')),
  UNIQUE (rag_id, level, depth)
);

-- ---------- สินค้า ----------
CREATE TABLE IF NOT EXISTS skus (
  sku_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku_code   TEXT NOT NULL UNIQUE,
  sku_name   TEXT NOT NULL,
  category   TEXT,
  unit       TEXT NOT NULL DEFAULT 'ชิ้น',
  barcode    TEXT,
  status     TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);

-- ---------- สินค้าที่จัดเก็บอยู่ในตำแหน่ง (1 ตำแหน่ง = 1 รายการ) ----------
CREATE TABLE IF NOT EXISTS stock_items (
  item_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku_id      INTEGER NOT NULL REFERENCES skus(sku_id),
  location_id INTEGER UNIQUE REFERENCES locations(location_id),   -- NULL = หยิบออกไปแล้ว
  lot_no      TEXT,
  exp_date    DATE,
  quantity    INTEGER NOT NULL CHECK (quantity >= 0),
  note        TEXT,
  status      TEXT NOT NULL DEFAULT 'IN_STOCK' CHECK (status IN ('IN_STOCK','REMOVED')),
  stored_at   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok'),
  updated_at  TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);

-- ---------- ประวัติการเคลื่อนย้าย (ลบและแก้ไขไม่ได้) ----------
CREATE TABLE IF NOT EXISTS movements (
  movement_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movement_type    TEXT NOT NULL CHECK (movement_type IN ('STORE','REMOVE','MOVE','EDIT')),
  moved_at         TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok'),
  item_id          INTEGER REFERENCES stock_items(item_id),
  sku_id           INTEGER NOT NULL REFERENCES skus(sku_id),
  lot_no           TEXT,
  quantity         INTEGER,
  from_location_id INTEGER REFERENCES locations(location_id),
  to_location_id   INTEGER REFERENCES locations(location_id),
  user_id          INTEGER NOT NULL REFERENCES users(user_id),
  note             TEXT
);

-- ประวัติต้องแก้ไข/ลบไม่ได้ (แทน RAISE(ABORT) ของ SQLite)
CREATE OR REPLACE FUNCTION trg_movements_immutable() RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'ประวัติการเคลื่อนย้ายแก้ไขหรือลบไม่ได้';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_movement_no_update ON movements;
CREATE TRIGGER trg_movement_no_update BEFORE UPDATE ON movements
  FOR EACH ROW EXECUTE FUNCTION trg_movements_immutable();

DROP TRIGGER IF EXISTS trg_movement_no_delete ON movements;
CREATE TRIGGER trg_movement_no_delete BEFORE DELETE ON movements
  FOR EACH ROW EXECUTE FUNCTION trg_movements_immutable();

-- ============================================================
-- ส่วนขยายตาม SRS (Inventory & Warehouse) — เพิ่มแบบ idempotent
-- ============================================================

-- ---------- เฟส 1: โครงสร้างข้อมูล ----------
-- ประเภทสินค้า (RM/PM/SEMI/FG/POSM) + อายุสินค้า (เดือน) + วันผลิตของแต่ละ Lot
ALTER TABLE skus ADD COLUMN IF NOT EXISTS product_type TEXT
  CHECK (product_type IN ('RM','PM','SEMI','FG','POSM'));
ALTER TABLE skus ADD COLUMN IF NOT EXISTS shelf_life_months INTEGER CHECK (shelf_life_months > 0);
ALTER TABLE stock_items ADD COLUMN IF NOT EXISTS mfg_date DATE;

-- ต้นทุนต่อหน่วย — ใช้ตีมูลค่าสต๊อกและมูลค่าความเสี่ยงของหมดอายุเป็นเงินบาท
-- เว้นว่างได้ ระบบจะรายงานเป็นจำนวนหน่วยแทน
ALTER TABLE skus ADD COLUMN IF NOT EXISTS unit_cost NUMERIC(12,2) CHECK (unit_cost >= 0);

-- หน่วยนับเพิ่มเติมต่อสินค้า (หน่วยฐานคือ skus.unit) เช่น 1 ลัง = 12 ชิ้น
CREATE TABLE IF NOT EXISTS sku_units (
  sku_unit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku_id      INTEGER NOT NULL REFERENCES skus(sku_id) ON DELETE CASCADE,
  unit_name   TEXT NOT NULL,
  factor      NUMERIC NOT NULL CHECK (factor > 0),   -- 1 หน่วยนี้ = กี่หน่วยฐาน
  UNIQUE (sku_id, unit_name)
);

-- ---------- เฟส 2: ช่องทางขาย + กฎอายุคงเหลือ ----------
CREATE TABLE IF NOT EXISTS channels (
  channel_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_code      TEXT NOT NULL UNIQUE,
  channel_name      TEXT NOT NULL,
  min_pct_remaining INTEGER CHECK (min_pct_remaining BETWEEN 0 AND 100),  -- NULL = ไม่จำกัด
  status            TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE'))
);

-- ค่าตั้งระบบ (threshold ต่าง ๆ แก้ได้จากหน้าตั้งค่า)
CREATE TABLE IF NOT EXISTS app_settings (
  key   TEXT PRIMARY KEY,
  value TEXT
);
INSERT INTO app_settings (key, value) VALUES
  ('expiry_move_months', '12'),    -- อายุต่ำกว่านี้ (เดือน) → แนะนำย้ายเข้าโซน/คลัง PROM
  ('expiry_cutoff_months', '4')    -- อายุต่ำกว่านี้ (เดือน) → แนะนำตัดออกจากระบบ
ON CONFLICT (key) DO NOTHING;

INSERT INTO channels (channel_code, channel_name, min_pct_remaining)
SELECT * FROM (VALUES
  ('MT', 'Modern Trade', 80),
  ('GT', 'General Trade', 50)
) AS v(code, name, pct)
WHERE NOT EXISTS (SELECT 1 FROM channels);

-- ---------- เฟส 3+4: เอกสารคลัง (รับเข้า/จ่ายออก/โอน/คืน/ตัดเสีย/ปรับยอด) ----------
CREATE TABLE IF NOT EXISTS documents (
  doc_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_type     TEXT NOT NULL CHECK (doc_type IN ('GRN','ISSUE','TRANSFER','RETURN_IN','RETURN_OUT','SCRAP','ADJUST')),
  doc_no       TEXT NOT NULL UNIQUE,
  ref_no       TEXT,       -- เลข PO / SO / MO อ้างอิง (จาก Express/Odoo)
  party        TEXT,       -- ชื่อ Supplier / ลูกค้า
  channel_id   INTEGER REFERENCES channels(channel_id),
  reason       TEXT,       -- เหตุผล (รับคืน/ตัดเสีย)
  qc_status    TEXT CHECK (qc_status IN ('PASS','FAIL','QUARANTINE')),
  qc_note      TEXT,
  note         TEXT,
  status       TEXT NOT NULL DEFAULT 'CONFIRMED' CHECK (status IN ('CONFIRMED','CANCELLED')),
  -- pipeline จ่ายออก (เฉพาะ doc_type = 'ISSUE'): Picked → Packed → Shipped → Delivered
  ship_status  TEXT CHECK (ship_status IN ('PICKED','PACKED','SHIPPED','DELIVERED')),
  tracking_no  TEXT,
  carrier      TEXT,
  picked_at    TIMESTAMP,
  packed_at    TIMESTAMP,
  shipped_at   TIMESTAMP,
  delivered_at TIMESTAMP,
  created_by   INTEGER REFERENCES users(user_id),
  created_at   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);
ALTER TABLE movements ADD COLUMN IF NOT EXISTS doc_id INTEGER REFERENCES documents(doc_id);

-- ---------- เฟส 5: รอบนับสต็อก (Cycle Count) ----------
CREATE TABLE IF NOT EXISTS count_rounds (
  round_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  round_no     TEXT NOT NULL UNIQUE,
  warehouse_id INTEGER REFERENCES warehouses(warehouse_id),
  zone_id      INTEGER REFERENCES zones(zone_id),
  note         TEXT,
  status       TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','APPROVED','CANCELLED')),
  created_by   INTEGER REFERENCES users(user_id),
  created_at   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok'),
  approved_by  INTEGER REFERENCES users(user_id),
  approved_at  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS count_lines (
  line_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  round_id     INTEGER NOT NULL REFERENCES count_rounds(round_id) ON DELETE CASCADE,
  location_id  INTEGER NOT NULL REFERENCES locations(location_id),
  item_id      INTEGER REFERENCES stock_items(item_id),
  sku_id       INTEGER REFERENCES skus(sku_id),
  lot_no       TEXT,
  expected_qty INTEGER NOT NULL DEFAULT 0,
  counted_qty  INTEGER,      -- NULL = ยังไม่ได้นับ
  note         TEXT,
  UNIQUE (round_id, location_id)
);

-- ---------- Index สำหรับการค้นหา ----------
CREATE INDEX IF NOT EXISTS idx_item_sku    ON stock_items(sku_id);
CREATE INDEX IF NOT EXISTS idx_item_status ON stock_items(status);
CREATE INDEX IF NOT EXISTS idx_item_lot    ON stock_items(lot_no);
CREATE INDEX IF NOT EXISTS idx_loc_rag     ON locations(rag_id, level, depth);
CREATE INDEX IF NOT EXISTS idx_loc_status  ON locations(status);
CREATE INDEX IF NOT EXISTS idx_sku_name    ON skus(sku_name);
CREATE INDEX IF NOT EXISTS idx_move_time   ON movements(moved_at);
CREATE INDEX IF NOT EXISTS idx_move_sku    ON movements(sku_id);
CREATE INDEX IF NOT EXISTS idx_move_item   ON movements(item_id);

-- ค้นหาข้อความภาษาไทยแบบ substring ให้เร็ว (ILIKE '%คำค้น%')
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_sku_name_trgm  ON skus USING gin (sku_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_sku_code_trgm  ON skus USING gin (sku_code gin_trgm_ops);

-- ---------- มุมมองรวม: สินค้าที่อยู่ในคลังพร้อมตำแหน่ง ----------
-- pct_remaining = % อายุคงเหลือ — คิดจากช่วง MFG→EXP ของ Lot ถ้ามีวันผลิต
--                 ไม่มีวันผลิตให้คิดจาก shelf life ของสินค้า (เดือน × 30.44 วัน)
-- นิยาม v_stock ย้ายไปอยู่ท้ายไฟล์ (เฟส 4) เพราะต้องรองรับพื้นราบและพาเลทด้วย
-- เก็บไว้ที่เดียวเพื่อกันกรณี CREATE OR REPLACE ทับกันแล้วชนเรื่องชื่อคอลัมน์

-- ---------- ปิดการเข้าถึงจากภายนอกทั้งหมด ----------
-- ระบบนี้ต่อฐานข้อมูลตรงด้วยบัญชี postgres และมีระบบสิทธิ์ของตัวเองอยู่แล้ว
-- จึงต้องเปิด RLS ไว้เสมอ เพื่อไม่ให้ anon key (ซึ่งเป็นกุญแจสาธารณะ) แตะข้อมูลได้
ALTER TABLE users        ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions     ENABLE ROW LEVEL SECURITY;
ALTER TABLE warehouses   ENABLE ROW LEVEL SECURITY;
ALTER TABLE zones        ENABLE ROW LEVEL SECURITY;
ALTER TABLE rags         ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations    ENABLE ROW LEVEL SECURITY;
ALTER TABLE skus         ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_items  ENABLE ROW LEVEL SECURITY;
ALTER TABLE movements    ENABLE ROW LEVEL SECURITY;
ALTER TABLE sku_units    ENABLE ROW LEVEL SECURITY;
ALTER TABLE channels     ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents    ENABLE ROW LEVEL SECURITY;
ALTER TABLE count_rounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE count_lines  ENABLE ROW LEVEL SECURITY;

-- Index สำหรับตารางใหม่
CREATE INDEX IF NOT EXISTS idx_doc_type   ON documents(doc_type, created_at);
CREATE INDEX IF NOT EXISTS idx_move_doc   ON movements(doc_id);
CREATE INDEX IF NOT EXISTS idx_count_round ON count_lines(round_id);

-- ============================================================
-- เฟส 4: พื้นที่ราบ + พาเลท + เศษที่แกะจากลัง
--
-- เดิมทุกตำแหน่งต้องอยู่บนชั้นวาง (locations.rag_id NOT NULL) แต่ของจริง
-- มีทั้งวางบนพื้นราบและของที่แกะลังแล้วเหลือเป็นเศษ จึงขยายให้ครบทั้งสามแบบ:
--   RACK  = ตำแหน่งบนชั้นวาง (เหมือนเดิม)
--   FLOOR = พื้นที่ราบ วางพาเลทบนพื้น
--   BREAK = พื้นที่พิเศษสำหรับของที่แกะออกจากลังแล้ว (เศษไม่ครบลัง)
-- ============================================================

ALTER TABLE zones ADD COLUMN IF NOT EXISTS zone_type TEXT NOT NULL DEFAULT 'RACK'
  CHECK (zone_type IN ('RACK','FLOOR','BREAK'));

-- ตำแหน่งบนพื้นราบไม่มีชั้นวาง จึงต้องผูกโซนตรง ๆ และให้ rag_id ว่างได้
ALTER TABLE locations ALTER COLUMN rag_id DROP NOT NULL;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS zone_id INTEGER REFERENCES zones(zone_id);
ALTER TABLE locations ADD COLUMN IF NOT EXISTS slot_no INTEGER;   -- ช่องที่เท่าไรในโซนพื้นราบ

-- ตำแหน่งเดิมทั้งหมดอยู่บนชั้นวาง — เติมโซนย้อนหลังจากชั้นวางที่สังกัด
UPDATE locations l SET zone_id = r.zone_id
  FROM rags r WHERE r.rag_id = l.rag_id AND l.zone_id IS NULL;

-- 1 SKU บรรจุได้กี่ลังต่อ 1 พาเลท — ใช้ตอนรับเข้าเพื่อคำนวณว่าต้องใช้กี่พาเลท
ALTER TABLE skus ADD COLUMN IF NOT EXISTS cartons_per_pallet INTEGER CHECK (cartons_per_pallet > 0);

-- ---------- พาเลท ----------
-- 1 พาเลท = สินค้า 1 SKU + 1 Lot เท่านั้น (ห้ามคละ) สร้างตอนรับเข้า
CREATE TABLE IF NOT EXISTS pallets (
  pallet_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pallet_no  TEXT NOT NULL UNIQUE,               -- เช่น PL-6909-0001
  sku_id     INTEGER NOT NULL REFERENCES skus(sku_id),
  lot_no     TEXT,
  mfg_date   DATE,
  exp_date   DATE,
  doc_id     INTEGER REFERENCES documents(doc_id),  -- ใบรับเข้าที่สร้างพาเลทนี้
  note       TEXT,
  status     TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','EMPTY')),
  created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);

-- ของที่จัดเก็บผูกกับพาเลทได้ และบอกได้ว่าเป็นเศษที่แกะจากลังแล้วหรือไม่
ALTER TABLE stock_items ADD COLUMN IF NOT EXISTS pallet_id INTEGER REFERENCES pallets(pallet_id);
ALTER TABLE stock_items ADD COLUMN IF NOT EXISTS is_loose BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_pallet_sku  ON pallets(sku_id, lot_no);
CREATE INDEX IF NOT EXISTS idx_loc_zone    ON locations(zone_id);
CREATE INDEX IF NOT EXISTS idx_item_pallet ON stock_items(pallet_id);

-- ---------- v_stock ใหม่ — รองรับทั้งชั้นวางและพื้นราบ ----------
-- ต้อง LEFT JOIN rags เพราะตำแหน่งพื้นราบไม่มีชั้นวาง และเอาโซนจาก locations ตรง ๆ
DROP VIEW IF EXISTS v_stock;
CREATE VIEW v_stock AS
SELECT i.item_id, i.lot_no, i.exp_date, i.quantity, i.note, i.stored_at,
       i.pallet_id, i.is_loose, p.pallet_no,
       s.sku_id, s.sku_code, s.sku_name, s.category, s.unit,
       l.location_id, l.location_code, l.level, l.depth, l.slot_no,
       r.rag_id, r.rag_no, z.zone_id, z.zone_code, z.zone_name, z.zone_type,
       w.warehouse_id, w.wh_code, w.wh_name,
       CASE WHEN i.exp_date IS NULL THEN NULL
            ELSE (i.exp_date - (now() AT TIME ZONE 'Asia/Bangkok')::date) END AS days_to_expiry,
       i.mfg_date, s.product_type, s.shelf_life_months, s.cartons_per_pallet,
       CASE WHEN i.exp_date IS NULL THEN NULL
            WHEN i.mfg_date IS NOT NULL AND i.exp_date > i.mfg_date THEN
              ROUND(100.0 * (i.exp_date - (now() AT TIME ZONE 'Asia/Bangkok')::date) / (i.exp_date - i.mfg_date))
            WHEN s.shelf_life_months IS NOT NULL THEN
              ROUND(100.0 * (i.exp_date - (now() AT TIME ZONE 'Asia/Bangkok')::date) / (s.shelf_life_months * 30.44))
            ELSE NULL END AS pct_remaining
FROM stock_items i
JOIN skus s      ON s.sku_id = i.sku_id
JOIN locations l ON l.location_id = i.location_id
JOIN zones z     ON z.zone_id = l.zone_id
LEFT JOIN rags r ON r.rag_id = l.rag_id
LEFT JOIN pallets p ON p.pallet_id = i.pallet_id
LEFT JOIN warehouses w ON w.warehouse_id = z.warehouse_id
WHERE i.status = 'IN_STOCK';

ALTER TABLE pallets ENABLE ROW LEVEL SECURITY;
