-- ============================================================
-- ระบบบริหารจัดการชั้นวางสินค้า (RAG) — โครงสร้างฐานข้อมูล PostgreSQL
-- แปลงจาก schema.sql (SQLite) สำหรับใช้กับ Supabase
--
-- แนวคิดเหมือนเดิม: ตำแหน่งจัดเก็บ 1 ช่อง เก็บสินค้าได้ 1 รายการ
--                  ทุกการเคลื่อนย้ายถูกบันทึกเป็นประวัติที่ลบไม่ได้
--
-- หมายเหตุเรื่องเวลา: ใช้ (now() AT TIME ZONE 'Asia/Bangkok') ทุกจุด จึงได้เวลาไทยเสมอ
--                    ไม่ขึ้นกับ session timezone เหมือน datetime('now','localtime') เดิม
-- ============================================================

-- ---------- ผู้ใช้งาน ----------
CREATE TABLE IF NOT EXISTS users (
  user_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT NOT NULL UNIQUE,
  full_name     TEXT NOT NULL,
  role          TEXT NOT NULL CHECK (role IN ('ADMIN','STAFF','VIEWER')),
  password_hash TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at    TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);

CREATE TABLE IF NOT EXISTS sessions (
  token      TEXT PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(user_id),
  expires_at TIMESTAMP NOT NULL
);

-- ---------- โครงสร้างคลัง: คลังสินค้า → โซน → ชั้นวาง (RACK) → ตำแหน่ง ----------
CREATE TABLE IF NOT EXISTS warehouses (
  warehouse_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wh_code      TEXT NOT NULL UNIQUE,
  wh_name      TEXT NOT NULL,
  address      TEXT,
  grid_cols    INTEGER NOT NULL DEFAULT 10 CHECK (grid_cols BETWEEN 1 AND 40),
  grid_rows    INTEGER NOT NULL DEFAULT 8  CHECK (grid_rows BETWEEN 1 AND 40),
  note         TEXT,
  status       TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);

-- warehouse_id / color เดิมเพิ่มด้วย ALTER TABLE ใน SQLite — ที่นี่ประกาศตรง ๆ ได้เลย
CREATE TABLE IF NOT EXISTS zones (
  zone_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_code    TEXT NOT NULL UNIQUE,
  zone_name    TEXT NOT NULL,
  warehouse_id INTEGER REFERENCES warehouses(warehouse_id),
  color        TEXT NOT NULL DEFAULT '#2563eb',
  status       TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);

CREATE TABLE IF NOT EXISTS rags (
  rag_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rag_no       TEXT NOT NULL UNIQUE,
  zone_id      INTEGER NOT NULL REFERENCES zones(zone_id),
  total_levels INTEGER NOT NULL CHECK (total_levels BETWEEN 1 AND 20),
  total_depths INTEGER NOT NULL CHECK (total_depths BETWEEN 1 AND 30),
  note         TEXT,
  pos_x        INTEGER,   -- ตำแหน่งบนผังพื้นคลัง (คอลัมน์)
  pos_y        INTEGER,   -- ตำแหน่งบนผังพื้นคลัง (แถว)
  status       TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);

CREATE TABLE IF NOT EXISTS locations (
  location_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_code TEXT NOT NULL UNIQUE,          -- เช่น FG-A01-L2-D3
  rag_id        INTEGER NOT NULL REFERENCES rags(rag_id) ON DELETE CASCADE,
  level         INTEGER NOT NULL,              -- ชั้น (1 = ล่างสุด)
  depth         INTEGER NOT NULL,              -- ตอน (1 = หน้าสุด)
  status        TEXT NOT NULL DEFAULT 'EMPTY' CHECK (status IN ('EMPTY','OCCUPIED','DISABLED')),
  UNIQUE (rag_id, level, depth)
);

-- ---------- สินค้า ----------
CREATE TABLE IF NOT EXISTS skus (
  sku_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku_code   TEXT NOT NULL UNIQUE,
  sku_name   TEXT NOT NULL,
  category   TEXT,
  unit       TEXT NOT NULL DEFAULT 'ชิ้น',
  barcode    TEXT,
  status     TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);

-- ---------- สินค้าที่จัดเก็บอยู่ในตำแหน่ง (1 ตำแหน่ง = 1 รายการ) ----------
CREATE TABLE IF NOT EXISTS stock_items (
  item_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku_id      INTEGER NOT NULL REFERENCES skus(sku_id),
  location_id INTEGER UNIQUE REFERENCES locations(location_id),   -- NULL = หยิบออกไปแล้ว
  lot_no      TEXT,
  exp_date    DATE,
  quantity    INTEGER NOT NULL CHECK (quantity >= 0),
  note        TEXT,
  status      TEXT NOT NULL DEFAULT 'IN_STOCK' CHECK (status IN ('IN_STOCK','REMOVED')),
  stored_at   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok'),
  updated_at  TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok')
);

-- ---------- ประวัติการเคลื่อนย้าย (ลบและแก้ไขไม่ได้) ----------
CREATE TABLE IF NOT EXISTS movements (
  movement_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movement_type    TEXT NOT NULL CHECK (movement_type IN ('STORE','REMOVE','MOVE','EDIT')),
  moved_at         TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Bangkok'),
  item_id          INTEGER REFERENCES stock_items(item_id),
  sku_id           INTEGER NOT NULL REFERENCES skus(sku_id),
  lot_no           TEXT,
  quantity         INTEGER,
  from_location_id INTEGER REFERENCES locations(location_id),
  to_location_id   INTEGER REFERENCES locations(location_id),
  user_id          INTEGER NOT NULL REFERENCES users(user_id),
  note             TEXT
);

-- ประวัติต้องแก้ไข/ลบไม่ได้ (แทน RAISE(ABORT) ของ SQLite)
CREATE OR REPLACE FUNCTION trg_movements_immutable() RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'ประวัติการเคลื่อนย้ายแก้ไขหรือลบไม่ได้';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_movement_no_update ON movements;
CREATE TRIGGER trg_movement_no_update BEFORE UPDATE ON movements
  FOR EACH ROW EXECUTE FUNCTION trg_movements_immutable();

DROP TRIGGER IF EXISTS trg_movement_no_delete ON movements;
CREATE TRIGGER trg_movement_no_delete BEFORE DELETE ON movements
  FOR EACH ROW EXECUTE FUNCTION trg_movements_immutable();

-- ---------- Index สำหรับการค้นหา ----------
CREATE INDEX IF NOT EXISTS idx_item_sku    ON stock_items(sku_id);
CREATE INDEX IF NOT EXISTS idx_item_status ON stock_items(status);
CREATE INDEX IF NOT EXISTS idx_item_lot    ON stock_items(lot_no);
CREATE INDEX IF NOT EXISTS idx_loc_rag     ON locations(rag_id, level, depth);
CREATE INDEX IF NOT EXISTS idx_loc_status  ON locations(status);
CREATE INDEX IF NOT EXISTS idx_sku_name    ON skus(sku_name);
CREATE INDEX IF NOT EXISTS idx_move_time   ON movements(moved_at);
CREATE INDEX IF NOT EXISTS idx_move_sku    ON movements(sku_id);
CREATE INDEX IF NOT EXISTS idx_move_item   ON movements(item_id);

-- ค้นหาข้อความภาษาไทยแบบ substring ให้เร็ว (ILIKE '%คำค้น%')
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_sku_name_trgm  ON skus USING gin (sku_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_sku_code_trgm  ON skus USING gin (sku_code gin_trgm_ops);

-- ---------- มุมมองรวม: สินค้าที่อยู่ในคลังพร้อมตำแหน่ง ----------
CREATE OR REPLACE VIEW v_stock AS
SELECT i.item_id, i.lot_no, i.exp_date, i.quantity, i.note, i.stored_at,
       s.sku_id, s.sku_code, s.sku_name, s.category, s.unit,
       l.location_id, l.location_code, l.level, l.depth,
       r.rag_id, r.rag_no, z.zone_id, z.zone_code, z.zone_name,
       w.warehouse_id, w.wh_code, w.wh_name,
       CASE WHEN i.exp_date IS NULL THEN NULL
            ELSE (i.exp_date - (now() AT TIME ZONE 'Asia/Bangkok')::date) END AS days_to_expiry
FROM stock_items i
JOIN skus s      ON s.sku_id = i.sku_id
JOIN locations l ON l.location_id = i.location_id
JOIN rags r      ON r.rag_id = l.rag_id
JOIN zones z     ON z.zone_id = r.zone_id
LEFT JOIN warehouses w ON w.warehouse_id = z.warehouse_id
WHERE i.status = 'IN_STOCK';

-- ---------- ปิดการเข้าถึงจากภายนอกทั้งหมด ----------
-- ระบบนี้ต่อฐานข้อมูลตรงด้วยบัญชี postgres และมีระบบสิทธิ์ของตัวเองอยู่แล้ว
-- จึงต้องเปิด RLS ไว้เสมอ เพื่อไม่ให้ anon key (ซึ่งเป็นกุญแจสาธารณะ) แตะข้อมูลได้
ALTER TABLE users       ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions    ENABLE ROW LEVEL SECURITY;
ALTER TABLE warehouses  ENABLE ROW LEVEL SECURITY;
ALTER TABLE zones       ENABLE ROW LEVEL SECURITY;
ALTER TABLE rags        ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations   ENABLE ROW LEVEL SECURITY;
ALTER TABLE skus        ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE movements   ENABLE ROW LEVEL SECURITY;
